import { ClientProviders } from '@/app/providers/client-providers';
import '@/app/styles/index.scss';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Simple App: Mark Melior',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='ru'>
			<body className={inter.className}>
				<ClientProviders>
					<AntdRegistry>{children}</AntdRegistry>
				</ClientProviders>
			</body>
		</html>
	);
}
